language: r
cache: packages
sudo: required
apt_packages:
  - libudunits2-dev
  - gdal-bin
  - libgdal-dev
  
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update -q
  